```markdown
# Tensor Basics
```

In [2]:
import torch
torch.__version__

'2.2.1+cu121'

In [2]:
import numpy as np

# filter warnings
import warnings
warnings.filterwarnings("ignore")

**Tensor Operations**
```markdown
- Addition 
- Subtraction
- Multiplication
- Division
- Matrix Multiplication
```

In [20]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
# Addition
tensor + 10 
torch.add(tensor, 10)
torch.add(tensor, tensor)


tensor([2, 4, 6])

In [21]:
# Subtraction
# tensor - 10
# tensor.sub(10)
# tensor - tensor
torch.sub(tensor, tensor+1)

tensor([-1, -1, -1])

In [ ]:
# Mulitplication
# tensor * 10
# torch.mul(tensor, 10)
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [ ]:
# Division
# tensor / 10
# tensor.div(10)
torch.div(tensor, tensor*5)

tensor([0.2000, 0.2000, 0.2000])

In [64]:
# reassign to persist changes
tensor = tensor + 10
tensor

tensor([11, 12, 13])

**Matrix Multiplication**

`torch.matmul()` or `@` or `torch.mm()`
```python
3x4 @ 4x3 = 3x3
3x2 @ 4x3 > Error

```

In [25]:
tensor = torch.tensor([1, 2, 3])
tensor.shape, tensor.dtype
tensor @ tensor


tensor(14)

In [26]:
# matmul
tensorA = torch.ones((2, 3))
tensorB = torch.ones((3, 2))

print(f"tensorA: {tensorA.shape}, tensorB: {tensorB.shape}")

new_tensor = torch.matmul(tensorA, tensorB)
new_tensor = tensorA @ tensorB
new_tensor = tensorA.mm(tensorB)
new_tensor

tensorA: torch.Size([2, 3]), tensorB: torch.Size([3, 2])


tensor([[3., 3.],
        [3., 3.]])

In [3]:
# matmul
tensorA = torch.ones((2, 3))
tensorB = torch.ones((2, 3))
tensorB = torch.ones((3, 2), device=torch.device('cuda'))
tensorB = tensorB.type(torch.float32)
tensorB = tensorB.to(torch.float32)
tensorB = tensorB.to(device='cpu', dtype=torch.float32)

# # new_tensor = tensorA @ tensorB
# new_tensor

''' Tensors need to have compatible shapes, dtypes and devices to be multiplied together.'''

' Tensors need to have compatible shapes, dtypes and devices to be multiplied together.'

In [ ]:
# carefull with shapes

tensorA = torch.ones((1,2, 3))
tensorB = torch.ones((3, 2))

print(f"tensorA: {tensorA.shape}, tensorB: {tensorB.shape}")
new_tensor = tensorA @ tensorB
# new_tensor = torch.transpose(tensorA,2,1) @ tensorB
new_tensor.shape

**Implemented operations are usually faster (avoid loops)**


In [109]:
%%time
# Matrix multiplication by hand 
tensor=torch.arange(1, 10)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 14.9 ms, sys: 959 µs, total: 15.8 ms
Wall time: 31.5 ms


tensor(285)

In [116]:
%%time
# Matrix multiplication by hand 
tensor=torch.arange(1, 10)
# value = torch.dot(tensor, tensor)
value = tensor @ tensor
value

CPU times: user 484 µs, sys: 187 µs, total: 671 µs
Wall time: 547 µs


tensor(285)

Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (feed-forward layer or fully connected layer), implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$


In [156]:
# Since the linear layer starts with a random weights matrix
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = torch.tensor([[1.0, 2.0], 
                  [3.0, 4.0], 
                  [5.0, 6.0]
                  ])
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")
print(f"weights: {linear.weight.shape} , bias: {linear.bias.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
weights: torch.Size([6, 2]) , bias: torch.Size([6])


**Aggregation**

```markdown
- Sum
- Mean
- Max
- Min
- Argmax
- Argmin
```

In [165]:
x = torch.arange(0, 100, 10).reshape(5, 2)
x

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [169]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") 
print(f"Sum: {x.sum(0)}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: tensor([200, 250])


In [170]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Reshape, Stack, Concatenate, Squeeze, Unsqueeze**


| Method | Description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 


In [192]:
# reshape
tensor = torch.arange(0, 100, 10)
print(f"Original tensor: {tensor, tensor.numel()}")
print(f"Reshaped tensor: {tensor.reshape(5, 2), tensor.reshape(5, 2).numel()}")


Original tensor: (tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), 10)
Reshaped tensor: (tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]]), 10)


In [196]:
# view
tensor = torch.arange(0, 100, 10)
print(f"Original tensor: {tensor, tensor.numel()}")
tensor_view = tensor.view(5, 2)

# changing the view changes the original tensor and vice versa
tensor[0] = 1000
print(f"Tensor After changing:{tensor}")
print(f"Tensor view After changing:{tensor_view}")

Original tensor: (tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), 10)
Tensor After changing:tensor([1000,   10,   20,   30,   40,   50,   60,   70,   80,   90])
Tensor view After changing:tensor([[1000,   10],
        [  20,   30],
        [  40,   50],
        [  60,   70],
        [  80,   90]])


In [232]:
# stack
x = torch.tensor([1, 2, 3])
print(x.size())

stacked = torch.stack((x, x, x,x,x), dim=0)
stacked, stacked.shape

torch.Size([3])


(tensor([[1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3]]),
 torch.Size([3, 5]))

In [198]:
# squeeze
tensor = torch.arange(0, 100, 10).reshape(1, 5,1,2, 1)
print(f"Original tensor: {tensor.shape}")
tensor_squeeze = tensor.squeeze()
print(f"Squeezed tensor: {tensor_squeeze.shape}")

Original tensor: torch.Size([1, 5, 1, 2, 1])
Squeezed tensor: torch.Size([5, 2])


In [205]:
# unsqueeze
tensor = torch.arange(0, 100, 10).reshape(5, 2)
print(f"Original tensor: {tensor.shape}")
tensor_unsqueeze = tensor.unsqueeze(dim=0)
print(f"Unsqueezed tensor: {tensor_unsqueeze.shape}")

Original tensor: torch.Size([5, 2])
Unsqueezed tensor: torch.Size([1, 5, 2])


In [238]:
# permute
tensor = torch.arange(0, 100, 10).reshape(5,1, 2,1)
print(f"Original tensor: {tensor.shape}")
new_tensor = tensor.permute(2, 0, 1, 3)
print(f"Permuted tensor: {new_tensor.shape}")

Original tensor: torch.Size([5, 1, 2, 1])
Permuted tensor: torch.Size([2, 5, 1, 1])


```markdown
## GPU operations
```


In [239]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [241]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"

# Count number of devices
torch.cuda.device_count()

1

In [242]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [243]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

device

'cuda'